# Generated by Django 4.2.30 on 2026-05-14 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("github", "GitHub"), ("local", "Local Path")],
                        default="github",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("canonical_url", models.URLField(blank=True, null=True, unique=True)),
                ("owner", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("default_branch", models.CharField(blank=True, max_length=100)),
                ("current_branch", models.CharField(blank=True, max_length=100)),
                ("current_commit_hash", models.CharField(blank=True, max_length=64)),
                ("local_path", models.TextField(blank=True)),
                ("source_file_count", models.PositiveIntegerField(default=0)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("not_synced", "Not Synced"),
                            ("syncing", "Syncing"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="not_synced",
                        max_length=30,
                    ),
                ),
                ("sync_error", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_analyzed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["source_type"], name="repositorie_source__ee854d_idx"
                    ),
                    models.Index(
                        fields=["sync_status"], name="repositorie_sync_st_e8547a_idx"
                    ),
                    models.Index(
                        fields=["owner", "name"], name="repositorie_owner_847fbf_idx"
                    ),
                    models.Index(
                        fields=["last_synced_at"], name="repositorie_last_sy_870b59_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "local")),
                fields=("source_type", "local_path"),
                name="unique_repository_source_local_path",
            ),
        ),
    ]
