# Generated by Django 4.2.30 on 2026-05-14 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("final_answer", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("answer_references", models.JSONField(blank=True, default=list)),
                ("llm_provider", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=150)),
                ("max_steps", models.PositiveIntegerField(default=8)),
                ("current_step", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tool_calls", models.PositiveIntegerField(default=0)),
                ("total_findings", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_sessions",
                        to="repositories.repository",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("database_reuse", "Database Reuse"),
                            ("system", "System"),
                        ],
                        default="agent",
                        max_length=30,
                    ),
                ),
                ("file_path", models.TextField()),
                ("symbol_name", models.CharField(blank=True, max_length=255)),
                ("symbol_type", models.CharField(blank=True, max_length=80)),
                ("line_start", models.PositiveIntegerField(blank=True, null=True)),
                ("line_end", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.TextField()),
                ("evidence_snippet", models.TextField(blank=True)),
                ("confidence", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="repositories.repository",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="research.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session_created", "Session Created"),
                            ("session_started", "Session Started"),
                            ("repository_synced", "Repository Synced"),
                            ("previous_findings_checked", "Previous Findings Checked"),
                            ("tool_started", "Tool Started"),
                            ("tool_completed", "Tool Completed"),
                            ("tool_failed", "Tool Failed"),
                            ("finding_saved", "Finding Saved"),
                            ("answer_started", "Answer Started"),
                            ("answer_completed", "Answer Completed"),
                            ("session_completed", "Session Completed"),
                            ("session_failed", "Session Failed"),
                            ("session_cancelled", "Session Cancelled"),
                        ],
                        default="session_created",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("step_number", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="research.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolCallLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tool_name", models.CharField(max_length=150)),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("code", "Code Exploration"),
                            ("database", "Database"),
                            ("llm", "LLM"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=30,
                    ),
                ),
                ("step_number", models.PositiveIntegerField(default=0)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("output_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="repositories.repository",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_calls",
                        to="research.researchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "step_number"],
                        name="research_to_session_c62bb7_idx",
                    ),
                    models.Index(
                        fields=["repository", "tool_name"],
                        name="research_to_reposit_ec91bb_idx",
                    ),
                    models.Index(
                        fields=["status"], name="research_to_status_a5cefe_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(
                fields=["repository", "-created_at"],
                name="research_re_reposit_2856d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(fields=["status"], name="research_re_status_6c4712_idx"),
        ),
        migrations.AddIndex(
            model_name="researchsession",
            index=models.Index(
                fields=["created_at"], name="research_re_created_561466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["session", "created_at"], name="research_fi_session_db7156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["repository", "file_path"],
                name="research_fi_reposit_97f7b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["source"], name="research_fi_source_79185b_idx"),
        ),
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(
                fields=["session", "created_at"], name="research_ag_session_7445a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(
                fields=["event_type"], name="research_ag_event_t_94f2f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentevent",
            index=models.Index(
                fields=["is_public"], name="research_ag_is_publ_08e4b6_idx"
            ),
        ),
    ]
